create table if not exists public.responses (
  id bigint generated by default as identity primary key,
  name varchar(255) not null,
  role varchar(100) not null,
  answers jsonb not null,
  submitted_at timestamptz not null default now()
);

create index if not exists responses_submitted_at_idx on public.responses (submitted_at desc);
